=== Vitilio/2122_LMSGI_VictorBR/public_html/ud4/EX02_20210309_VictorBR/mapaestelar.dtd
<!ELEMENT mapaestelar (constelacion,estrella)+>
<!ATTLIST mapaestelar
          xmlns:xsi CDATA #IMPLIED
          xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT constelacion (#PCDATA|nombre|superficie|estrellas|objetos|colindantes|observacion)*>
<!ATTLIST constelacion 
          nombreLatin CDATA #IMPLIED>
<!ELEMENT nombreEspanol (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT estrellas (asterismo,masBrillante)>
<!ATTLIST estrellas
          numEstrellas CDATA #IMPLIED>
<!ELEMENT asterismo (#PCDATA)>
<!ELEMENT masBrillante (#PCDATA)>
<!ATTLIST masBrillante
          luminosidad CDATA #REQUIRED>
<!ELEMENT objetos (cumulos,nebulosas,galaxias,cuasares,lluviaDeMeteoros*)>
<!ELEMENT cumulos (#PCDATA)>
<!ELEMENT nebulosas (#PCDATA)>
<!ELEMENT galaxias (#PCDATA)>
<!ELEMENT cuasares (#PCDATA)>
<!ELEMENT lluviaDeMeteoros (#PCDATA)>
<!ELEMENT colindantes (nombre+)>
<!ELEMENT observacion (hemisferio,mes,hora)>
<!ELEMENT hemisferio (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT estrella (nombre,constelacion,distancia,luminosidad,temperatura,masa)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia
          medida CDATA #FIXED "anyos luz">       
<!ELEMENT luminosidad (#PCDATA)>
<!ATTLIST luminosidad
          medida CDATA #FIXED "soles">       
<!ELEMENT temperatura (#PCDATA)>
<!ATTLIST temperatura
          medida CDATA #FIXED "K">       
<!ELEMENT masa (#PCDATA)>
<!ATTLIST masa
          medida CDATA #FIXED "soles">

=== Vitilio/2122_LMSGI_VictorBR/public_html/ud4/EX02_20210309_VictorBR/mapaestelar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapaestelar SYSTEM "mapaestelar.dtd">
<!--
Fallos
XML
mes->Es valor numerico no string 
lluviaDeMeteoros->No hay valor nombre, es multiple
DTD
(,)+ != (+,+)
Ante la duda #Implied
positiveInteger
minOccurs = 0 -> Opcional
-->

<mapaestelar xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
             xsi:noNamespaceSchemaLocation='mapaestelar.xsd'>
    <constelacion nombreLatin="Ursa Maior">
        <nombreEspanol>La Osa Mayor</nombreEspanol>
        <superficie>1279.7</superficie>
        <estrellas numEstrellas="209">
            <asterismo>7</asterismo>
            <masBrillante luminosidad="108">Alioth</masBrillante>
        </estrellas>
        <objetos>
            <cumulos>false</cumulos>
            <nebulosas>true</nebulosas>
            <galaxias>true</galaxias>
            <cuasares>false</cuasares>
            <lluviaDeMeteoros>Kappa Ursa May贸ridas</lluviaDeMeteoros>
            <lluviaDeMeteoros>Lambda Ursa May贸ridas</lluviaDeMeteoros>
            <lluviaDeMeteoros>Psi Ursa May贸ridas</lluviaDeMeteoros>
            <lluviaDeMeteoros>Ursa May贸ridas de octubre</lluviaDeMeteoros>
        </objetos>
        <colindantes>
            <nombre>Bootes</nombre>
            <nombre>Camelopardalis</nombre>
            <nombre>Canes Venatici</nombre>
            <nombre>Draco</nombre>
            <nombre>Leo</nombre>
            <nombre>Leo Minor</nombre>
            <nombre>Lynx</nombre>
        </colindantes>
        <observacion>
            <hemisferio>norte</hemisferio>
            <mes>--04</mes>
            <hora>21:00:00</hora>
        </observacion>
    </constelacion>
    <estrella>
        <nombre>Alioth</nombre>
        <constelacion>Osa Mayor</constelacion>
        <distancia medida="anyos luz">81</distancia>
        <luminosidad medida="soles">108</luminosidad>
        <temperatura medida="K">9400</temperatura>
        <masa medida="soles">3</masa>
    </estrella>
</mapaestelar>
