=== Vitilio/2122_LMSGI_VictorBR/public_html/ud4/03.dtd
<!ELEMENT hechosHistoricos (fila+)>
<!ATTLIST hechosHistoricos
          xmlns:xsi CDATA #IMPLIED
          xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT fila (descripcion+,fecha)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (dia,mes,anyo)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>

=== Vitilio/2122_LMSGI_VictorBR/public_html/ud4/03/03.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE hechosHistoricos SYSTEM "03.dtd">
    

<hechosHistoricos
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='03.xsd'>
    <fila>
        <descripcion>Se funda Youtube</descripcion>
        <fecha>
            <dia>15</dia>
            <mes>2</mes>
            <anyo>2005</anyo>
        </fecha>
    </fila>
    <fila>
        <descripcion>Se funda Google</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>9</mes>
            <anyo>1998</anyo>
        </fecha>
    </fila>
    <fila>
        <descripcion>Se funda Facebook</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <anyo>2004</anyo>
        </fecha>
    </fila>
</hechosHistoricos>
