=== Vitilio/2122_LMSGI_VictorBR/public_html/ud4/04.dtd
<!ELEMENT cvitae (nombre,apellidos,anyoNac,residencia,datosContacto)>
<!ATTLIST cvitae
          xmlns:xsi CDATA #IMPLIED
          xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT residencia (ciudad,pais)>
<!ELEMENT datosContacto (telefono,email,linkedin,descripcion,competencias,formaciones,experiencias)>
<!ELEMENT competencias (competencia+)>
<!ELEMENT competencia EMPTY>
<!ATTLIST competencia nombre CDATA #REQUIRED 
                       nivel (alto|medio|basico) "medio" >

<!ELEMENT formaciones (formacion+)>
<!ELEMENT formacion EMPTY>
<!ATTLIST formacion   titulacion CDATA #REQUIRED
                      centro CDATA #REQUIRED
                      anyo CDATA #IMPLIED>
<!ELEMENT experiencias (experiencia+)>
<!ELEMENT experiencia EMPTY>
<!ATTLIST experiencia puesto CDATA #REQUIRED
                      empresa CDATA #REQUIRED
                      anyoInicio CDATA #IMPLIED
                      anyoFinal CDATA #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT anyoNac (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT linkedin (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

=== Vitilio/2122_LMSGI_VictorBR/public_html/ud4/04.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE cvitae SYSTEM "04.dtd">

<cvitae
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='04.xsd'>
    <nombre>Victor</nombre>
    <apellidos>Blanco Rodrigo</apellidos>
    <anyoNac>2001</anyoNac>
    <residencia>
        <ciudad>Benavente</ciudad>
        <pais>Espa√±a</pais>
    </residencia>
    <datosContacto>
        <telefono>646275623</telefono>
        <email>victor.blarod@educa.jcyl.es</email>
        <linkedin>https://es.linkedin.com/VictorBlanco</linkedin>
        <descripcion>Estudiante</descripcion>
        <competencias>
            <competencia nombre="Creacion de bases de datos en MySQL" nivel="medio"/>
            <competencia nombre="Programacion en Java" nivel="medio"/>
            <competencia nombre="Desarollo de paginas web" nivel="basico"/>
        </competencias>
        <formaciones>
            <formacion titulacion="Bachillerato de Ciencias" centro="IES Los Sauces" anyo="2020"/>
            <formacion titulacion="B2" centro="EOI Benavente"/>
        </formaciones>
        <experiencias>
            <experiencia puesto="cajero" empresa="Burger King" anyoInicio="2015" anyoFinal="2017"/>
        </experiencias>
    </datosContacto>
</cvitae>
