=== Vitilio/2122_LMSGI_VictorBR/public_html/ud4/05.dtd
<!ELEMENT Company (Employee+)>
<!ATTLIST Company 
          xmlns:xsi CDATA #IMPLIED
          xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT Employee (FirstName,LastName,ContactNo,Email,Address)>
<!ELEMENT Address (City,State,Zip)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT ContactNo (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Zip (#PCDATA)>

=== Vitilio/2122_LMSGI_VictorBR/public_html/ud4/05.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE Company SYSTEM "05.dtd">
    
<Company
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='05.xsd'>
    <Employee>
        <FirstName>Juan</FirstName>
        <LastName>Sanchez</LastName>
        <ContactNo>123456789</ContactNo>
        <Email>juansanchez@company.com</Email>
        <Address>
            <City>Bangalore</City>
            <State>Karnataka</State>
            <Zip>560212</Zip>  
        </Address>
    </Employee>
</Company>
