=== Vitilio/2122_LMSGI_VictorBR/public_html/ud4/receta.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <!--Declaracion de tipos-->
    
    <!--Declaracion de elementos-->
    <xs:element name="receta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="descripcion" type="xs:string" minOccurs="0"/>
                <xs:element name="tiempo">
                    <xs:complexType>
                        <xs:attribute name="preparacion" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"/>
                                    <xs:maxInclusive value="999"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="coccion" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"/>
                                    <xs:maxInclusive value="999"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ingredientes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingrediente">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="cantidad" type="xs:positiveInteger" minOccurs="0">  
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="unidad" use="optional">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:pattern value="gramos|pizca|mililitros|cucharada|chorro"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="instrucciones" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="paso" type="xs:string" maxOccurs="10"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="plato" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="primero"/>
                        <xs:enumeration value="segundo"/>
                        <xs:enumeration value="postre"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Vitilio/2122_LMSGI_VictorBR/public_html/ud4/11/receta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE receta SYSTEM "receta.dtd">
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<receta plato="primero"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='receta.xsd'>
    <nombre>Risotto milanesa</nombre>
    <tiempo preparacion="30" coccion="20"></tiempo>
    <ingredientes>
        <ingrediente>
            <nombre>Arroz</nombre>
            <cantidad unidad="gramos">500</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>Cebolla mediana</nombre>
            <cantidad>1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>Azafran</nombre>
            <cantidad unidad="pizca">1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>Queso parmesano</nombre>
            <cantidad unidad="gramos">100</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>Mantequilla</nombre>
            <cantidad unidad="gramos">100</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>Sal</nombre>
        </ingrediente>
        <ingrediente>
            <nombre>Pimienta</nombre>
        </ingrediente>
        <ingrediente>
            <nombre>Caldo</nombre>
            <cantidad unidad="mililitros">1000</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>Vino blanco</nombre>
            <cantidad unidad="chorro">1</cantidad>
        </ingrediente>
    </ingredientes>
    <instrucciones>
        <paso>1.-Picamos la cebolla y la pochamos con la mitad
            de la mantequilla.</paso>
        <paso>2.-Cuando esté transparente, echamos el azafrán,
            el vino y dejamos que reduzca.</paso>
        <paso>3.-A continuación, incorporamos el arroz, lo
            sofreímos un poco.</paso>
        <paso>4.-Vamos añadiendo el caldo caliente poco a poco
            mientras removemos</paso>
        <paso>5.-Salpimentamos</paso>
        <paso>6.-Cuando esté casi hecho, agregamos el resto de
            la mantequilla y el queso</paso>
        <paso>7.-Servimos enseguida</paso>
    </instrucciones>
</receta>
